---
abstract: 'XMLish JSONish Ragel Powered Parser.'
author:
  - 'David Helkowski <cpan@codechild.com>'
build_requires:
  English: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Parse-XJR
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  DynaLoader: '0'
  Exporter: '0'
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
